Start:MOV P3, #0FFH
CLR P2.0
CLR P2.1
CheckIR: ACALL DELAY
MOV R7, P3
MOV A, R7
RRC A 
JNC MotorForward
SJMP CheckIR
BACK1: MOV R7, P3
MOV A, R7
RRC A 
RRC A
JNC SecondIRDetected 
SJMP BACK1
MotorForward:SETB P2.0
CLR P2.1
ACALL DELAY1
ACALL DELAY1 
ACALL DELAY
CLR P2.0
SJMP BACK1 
SecondIRDetected:MOV R6,P3
MOV A, R6 
RRC A 
RRC A 
JC MotorReverse_Check_FirstIR
SJMP SecondIRDetected
MotorReverse_Check_FirstIR:MOV R5,P3 
MOV A,R5 
RRC A
JNC MotorReverse_Check_FirstIR
SecondIR_Check:MOV R4,P3
MOV A,R4
RRC A 
RRC A 
JNC SecondIR_Check           
CLR P2.0
SETB P2.1 
ACALL DELAY1 
ACALL DELAY1 
ACALL DELAY 
CLR P2.1 
SJMP Start 
DELAY:MOV R7,#0FFH       
TOP:MOV R6,#0FFH 
MOV R5,#0FFH
BACK:DJNZ R5,BACK 
UP:DJNZ R6,UP 
DJNZ R7,TOP 
RET
DELAY1:MOV R4,#14H
OneSec:MOV TMOD,#01H 
MOV TL0,#0AFH 
MOV TH0,#3CH 
SETB TR0 
WAIT:JNB TF0,WAIT
CLR TR0 
CLR TF0
DJNZ R4,OneSec
RET 
END 